# Generated by Django 3.1.1 on 2020-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200924_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city_from', models.CharField(max_length=50)),
                ('nights', models.IntegerField(max_length=10)),
                ('persons', models.IntegerField(max_length=2)),
                ('price', models.IntegerField()),
                ('photo_0', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
