# Generated by Django 3.1.1 on 2020-10-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_newtour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtour',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='newtour',
            old_name='photo_0',
            new_name='tour_photo',
        ),
    ]
