# Generated by Django 3.1.1 on 2020-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201002_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newtour',
            options={'verbose_name': 'Нові тури', 'verbose_name_plural': 'Нові тури'},
        ),
        migrations.AlterField(
            model_name='newtour',
            name='city_from',
            field=models.CharField(max_length=50, verbose_name='Виліт з '),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='nights',
            field=models.IntegerField(max_length=10, verbose_name='Кількість ночей'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='persons',
            field=models.IntegerField(max_length=2, verbose_name='Кількість людей'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва туру'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='tour_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Постер'),
        ),
    ]
