# Generated by Django 3.1.1 on 2020-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201002_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtour',
            name='city_from',
            field=models.CharField(max_length=50, verbose_name='Виліт з'),
        ),
    ]
