# Generated by Django 3.1.1 on 2020-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201002_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtour',
            name='city_from',
        ),
        migrations.AddField(
            model_name='newtour',
            name='airport_from',
            field=models.CharField(choices=[('бориспіль', 'Київ-Бориспіль'), ('жуляни', 'Київ-Жуляни')], default='DEFAULT VALUE', max_length=100, verbose_name='Виліт з'),
        ),
        migrations.AddField(
            model_name='newtour',
            name='city',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='newtour',
            name='hotel',
            field=models.CharField(default='DEFAULT VALUE', max_length=100, verbose_name='Готель'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='nights',
            field=models.IntegerField(verbose_name='Кількість ночей'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='persons',
            field=models.IntegerField(verbose_name='Кількість людей'),
        ),
        migrations.AlterField(
            model_name='newtour',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва туру'),
        ),
    ]
