# Generated by Django 3.1.1 on 2020-10-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201002_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtour',
            name='is_hot_tour',
            field=models.BooleanField(default=False),
        ),
    ]
