# Generated by Django 3.1.1 on 2020-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_newtour_is_hot_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtour',
            name='rooms_class',
            field=models.CharField(choices=[('стандарт', 'Стандарт'), ('все всключено', 'все вклюено'), ('королівський люкс', 'Королівський люкс')], default='default', max_length=100, verbose_name='Тип готельного номеру'),
        ),
        migrations.AddField(
            model_name='newtour',
            name='to_airport',
            field=models.CharField(default='default', max_length=100, verbose_name='До аеропорту '),
        ),
    ]
